image:
- Visual Studio 2015

version: 1.0.{build}
#clone_folder: 'C:\Program Files\WindowsPowerShell\Modules\PSClassUtils\'

environment:
  PSgalleryKey:
    secure: wl8DNkBd6QUSBAEWxCNTTW+cVn32ub6kWSqZxAUrpx4/QPnWYGiLWEj+ZaFp5cuA
 
install:
- ps: >-
    .\CI\02_Install.ps1
build: off
test_script:
- ps: >-
    .\CI\03_Tests.ps1
